name: Package

permissions:
  contents: write

on:
  push:
    branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '*')"
    
    steps:
      - name: Install Checkout
        uses: actions/checkout@v1
      
      - name: Install Setup SP
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.13.x'
      
      - name: Get GitHub Env
        run: |
          echo "PLUGIN_VERSION_REVISION<<EOF" >> $GITHUB_ENV
          git rev-list --count HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Install Misc
        run: |
          bash scripts/setup.sh
          bash scripts/optional.sh
        working-directory: ./
      
      - name: Full Compile
        run: |
          mkdir -p plugins
          spcomp -E -O2 -v2 -i "include" -o "plugins/scpm.smx" scpm.sp
        working-directory: ${{ env.SCRIPTS_PATH }}
      
      - name: Setup Package
        run: bash scripts/package.sh
      
      - name: Package Full
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r New-Install-Package-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}.zip New-Install-Package
      
      - name: Package Update
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r Update-Package-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}.zip Update-Package
      
      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}
          files: |
            New-Install-Package-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}.zip
            Update-Package-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}.zip
  
  nonrelease:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '*')"
    
    steps:
      - name: Install Checkout
        uses: actions/checkout@v1
      
      - name: Install Setup SP
        uses: rumblefrog/setup-sp@master
        with:
          version: '1.13.x'
      
      - name: Get GitHub Env
        run: |
          echo "PLUGIN_VERSION_REVISION<<EOF" >> $GITHUB_ENV
          git rev-list --count HEAD >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Install Misc
        run: |
          bash scripts/setup.sh
          bash scripts/optional.sh
        working-directory: ./
      
      - name: Full Compile
        run: |
          mkdir -p plugins
          spcomp -E -O2 -v2 -i "include" -o "plugins/scpm.smx" scpm.sp
        working-directory: ${{ env.SCRIPTS_PATH }}
      
      - name: Setup Package
        run: bash scripts/package.sh
      
      - name: Upload Full
        uses: actions/upload-artifact@master
        with:
          name: New-Install-Package-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}
          path: ./New-Install-Package
      
      - name: Upload Update
        uses: actions/upload-artifact@master
        with:
          name: Update-Package-${{env.PLUGIN_VERSION}}.${{env.PLUGIN_VERSION_REVISION}}
          path: ./Update-Package
